### PR TITLE
fix: normalize invalid search exceptions outside JSON-LD context

### LINKED ISSUE #250: [ApiPlatform] Unable to generate a URL for the named route "api_jsonld_context" as such route does not exist.
**RollerworksSearch version(s) affected**: master

**Description**  
If JSON-LD is not enabled in API Platform, any search errors throw an exception:

```
Unable to generate a URL for the named route "api_jsonld_context" as such route does not exist.
```
due to https://github.com/rollerworks/search/blob/32f91d738e06461e1ddf63b3b37e242c20ddac5a/lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php#L67

**How to reproduce**  
Disable JSON-LD in API Platform, create any search exception.

**Possible Solution**  
Only attach JSON-LD properties if in JSON-LD context. Better yet, maybe delegate exception serialization to APIP?

### PR DESCRIPTION
**Pull request by dkarlovi**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #250 
| License       | MIT
| Doc PR        | N/A

Closes #250.

### CODE REVIEW

**Comment by dkarlovi** [comment]
@sstok do you have any idea why this would fail? It thinks only `application/json` is available.
https://travis-ci.org/rollerworks/search/jobs/467469661#L869

File: lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php [hunk 1]
```diff
@@ -27,53 +31,80 @@
...
-    public function supportsNormalization($data, $format = null)
+    public function supportsNormalization($data, $format = null): bool
     {
         return self::FORMAT === $format && $data instanceof InvalidSearchConditionException;
     }
+
+    /**
+     * @author Kévin Dunglas <dunglas@gmail.com>
+     *
+     * @see https://github.com/api-platform/core
```
Comment (dkarlovi) [inline lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php]: Added from an `@internal` abstract class which was only available since APIP 2.2, better to inline.

**Comment by dkarlovi** [comment]
@sstok ready for review, maybe even a new alpha tagged?

File: lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php [hunk 2]
```diff
@@ -27,53 +31,80 @@
...
 
     /**
-     * Normalizes an object into a set of arrays/scalars.
-     *
-     * @param InvalidSearchConditionException $object  object to normalize
-     * @param string                          $format  format the normalization result will be encoded as
-     * @param array                           $context Context options for the normalizer
-     *
-     * @return array
+     * @inheritdoc
```
Comment (sstok) [inline lib/ApiPlatform/Serializer/InvalidSearchConditionNormalizer.php]: No need for `@inheritdoc`, this is implicit and only applies to the description.

**Comment by sstok** [comment]
Thank you @dkarlovi
